# new Sport
Sport.delete_all

# Article Sport 1
@sport1 = Sport.new(name: "Padel")
@sport1.image.attach(io: Rails.root.join("vendor/assets/images/banners/banner-grey.png").open, filename: "banner-grey.png")
@sport1.short_description = "Padel (Spanish: pádel), also sometimes called padel tennis, is a racket sport that originates from Mexico, typically played in doubles on an enclosed court slightly smaller than a doubles tennis court.[1] Although padel shares the same scoring system as tennis, the rules, strokes, and technique are different. The balls used are similar but with a little less pressure. The main differences are that the court has walls and the balls can be played off them in a similar way as in the game of squash and that solid, stringless bats are used. The height of the ball being served must be at or below the waist level."
@sport1.description = "Padel tennis distinguishes itself not only through its gameplay but also through its unique style and atmosphere. Emerging from a blend of traditional tennis and squash, Padel offers a more relaxed and social environment compared to other racket sports. Unlike the formality often associated with tennis, Padel is characterised by its laid-back atmosphere, where players frequently enjoy casual wear and the presence of music on the courts. This casual ambiance contributes to the sport's growing popularity, attracting players of all ages and skill levels. The fast-paced nature of Padel, combined with its shorter court dimensions and the use of walls, fosters exciting and engaging gameplay, characterised by lengthy rallies and spirited crowd participation. The sport's allure lies not only in its accessibility but also in its ability to provide a fun and lively experience for players and spectators alike."
@sport1.save
Mobility.with_locale(:id) {
  @sport1.short_description = "Padel (bahasa Spanyol: pádel), juga terkadang disebut tenis padel, adalah olahraga raket yang berasal dari Meksiko, biasanya dimainkan secara ganda di lapangan tertutup yang sedikit lebih kecil dari lapangan tenis ganda.[1] Meskipun padel memiliki sistem penilaian yang sama dengan tenis, aturan, pukulan, dan tekniknya berbeda. Bola yang digunakan serupa tetapi dengan sedikit tekanan yang lebih rendah. Perbedaan utamanya adalah lapangan memiliki dinding dan bola dapat dimainkan di sana dengan cara yang sama seperti dalam permainan squash dan menggunakan tongkat pemukul yang kokoh dan tanpa tali. Ketinggian bola yang diservis harus berada di atau di bawah pinggang."
  @sport1.description = "Tenis Padel tidak hanya menonjolkan permainannya, tetapi juga gaya dan suasananya yang unik. Padel, yang merupakan perpaduan tenis tradisional dan squash, menawarkan lingkungan yang lebih santai dan sosial dibandingkan dengan olahraga raket lainnya. Tidak seperti formalitas yang sering dikaitkan dengan tenis, Padel dicirikan oleh suasananya yang santai, di mana para pemain sering kali menikmati pakaian kasual dan alunan musik di lapangan. Suasana kasual ini berkontribusi pada semakin populernya olahraga ini, yang menarik pemain dari segala usia dan tingkat keterampilan. Sifat Padel yang serba cepat, dipadukan dengan dimensi lapangan yang lebih pendek dan penggunaan dinding, mendorong permainan yang seru dan menarik, yang dicirikan oleh reli yang panjang dan partisipasi penonton yang bersemangat. Daya tarik olahraga ini tidak hanya terletak pada aksesibilitasnya, tetapi juga kemampuannya untuk memberikan pengalaman yang menyenangkan dan semarak bagi para pemain dan penonton."
}
@sport1.save
puts "new Sport: #{@sport1.name}"

# Article Sport 2
@sport2 = Sport.new(name: "Golf")
@sport2.image.attach(io: Rails.root.join("vendor/assets/images/banners/banner-grey.png").open, filename: "banner-grey.png")
@sport2.short_description = "Golf is a club-and-ball sport in which players use various clubs to hit a ball into a series of holes on a course in as few strokes as possible. Golf, unlike most ball games, cannot and does not use a standardized playing area, and coping with the varied terrains encountered on different courses is a key part of the game. Courses typically have either 9 or 18 holes, regions of terrain that each contain a cup, the hole that receives the ball. Each hole on a course has a teeing ground for the hole's first stroke, and a putting green containing the cup. There are several standard forms of terrain between the tee and the green, such as the fairway, rough (tall grass), and various hazards that may be water, rocks, or sand-filled bunkers. Each hole on a course is unique in its specific layout. Many golf courses are designed to resemble their native landscape, such as along a sea coast (where the course is called a links), within a forest, among rolling hills, or part of a desert."
@sport2.description = "Playing a hole on a golf course is initiated by putting a ball into play by striking it with a club on the teeing ground (also called the tee box, or simply the tee). For this first shot on each hole, it is allowed but not required for the golfer to place the ball on a tee prior to striking it. A tee is a small peg that can be used to elevate the ball slightly above the ground up to a few centimetres high. Tees are commonly made of wood but may be constructed of any material, including plastic. Traditionally, golfers used mounds of sand to elevate the ball, and containers of sand were provided for the purpose.[23][24] A few courses still require sand to be used instead of peg tees, to reduce litter and reduce damage to the teeing ground. Tees help reduce the interference of the ground or grass on the movement of the club making the ball easier to hit by elevating the ball from the playing surface"
@sport2.save
Mobility.with_locale(:id) {
  @sport2.short_description = "Golf adalah olahraga tongkat dan bola di mana pemain menggunakan berbagai tongkat untuk memukul bola ke serangkaian lubang di lapangan dalam sesedikit mungkin pukulan. Golf, tidak seperti kebanyakan permainan bola, tidak dapat dan tidak menggunakan area bermain standar, dan mengatasi berbagai medan yang ditemui di berbagai lapangan adalah bagian penting dari permainan. Lapangan biasanya memiliki 9 atau 18 lubang, wilayah medan yang masing-masing berisi cangkir, lubang yang menerima bola. Setiap lubang di lapangan memiliki teeing ground untuk pukulan pertama lubang, dan putting green yang berisi cangkir. Ada beberapa bentuk medan standar antara tee dan green, seperti fairway, rough (rumput tinggi), dan berbagai rintangan yang mungkin berupa air, bebatuan, atau bunker berisi pasir. Setiap lubang di lapangan memiliki tata letak yang unik. Banyak lapangan golf yang dirancang menyerupai lanskap asli mereka, seperti di sepanjang pantai laut (di mana lapangan disebut links), di dalam hutan, di antara perbukitan, atau bagian dari gurun."
  @sport2.description = "Memainkan hole di lapangan golf dimulai dengan meletakkan bola ke dalam permainan dengan memukulnya menggunakan tongkat golf di teeing ground (juga disebut tee box, atau hanya tee). Untuk pukulan pertama ini di setiap hole, pegolf diperbolehkan tetapi tidak diharuskan untuk meletakkan bola di tee sebelum memukulnya. Tee adalah pasak kecil yang dapat digunakan untuk mengangkat bola sedikit di atas tanah hingga setinggi beberapa sentimeter. Tee biasanya terbuat dari kayu tetapi dapat dibuat dari bahan apa saja, termasuk plastik. Secara tradisional, pegolf menggunakan gundukan pasir untuk mengangkat bola, dan wadah pasir disediakan untuk tujuan tersebut.[23][24] Beberapa lapangan masih mengharuskan pasir untuk digunakan sebagai pengganti peg tee, untuk mengurangi sampah dan mengurangi kerusakan pada teeing ground. Tee membantu mengurangi gangguan tanah atau rumput pada pergerakan tongkat golf sehingga bola lebih mudah dipukul dengan mengangkat bola dari permukaan bermain."
}
@sport2.save
puts "new Sport: #{@sport2.name}"

# Article Sport 3
@sport3 = Sport.new(name: "Tennis")
@sport3.image.attach(io: Rails.root.join("vendor/assets/images/banners/banner-grey.png").open, filename: "banner-grey.png")
@sport3.short_description = "Tennis is a racket sport that is played either individually against a single opponent (singles) or between two teams of two players each (doubles). Each player uses a tennis racket strung with a cord to strike a hollow rubber ball covered with felt over or around a net and into the opponent's court. The object is to manoeuvre the ball in such a way that the opponent is not able to play a valid return. If a player is unable to return the ball successfully, the opponent scores a point."
@sport3.description = "The components of a tennis racket include a handle, known as the grip, connected to a neck which joins a roughly elliptical frame that holds a matrix of tightly pulled strings. For the first 100 years of the modern game, rackets were made of wood and of standard size, and strings were of animal gut. Laminated wood construction yielded more strength in rackets used through most of the 20th century until first metal and then composites of carbon graphite, ceramics, and lighter metals such as titanium were introduced. These stronger materials enabled the production of oversized rackets that yielded yet more power. Meanwhile, technology led to the use of synthetic strings that match the feel of gut yet with added durability."
@sport3.save
Mobility.with_locale(:id) {
  @sport3.short_description = "Tenis adalah olahraga raket yang dimainkan secara individu melawan satu lawan (tunggal) atau antara dua tim yang masing-masing terdiri dari dua pemain (ganda). Setiap pemain menggunakan raket tenis yang diikat dengan tali untuk memukul bola karet berongga yang dilapisi kain felt di atas atau di sekitar net dan masuk ke lapangan lawan. Tujuannya adalah untuk mengarahkan bola sedemikian rupa sehingga lawan tidak dapat melakukan pengembalian yang valid. Jika seorang pemain tidak dapat mengembalikan bola dengan sukses, lawan mendapat poin."
  @sport3.description = "Komponen raket tenis meliputi pegangan, yang dikenal sebagai grip, yang terhubung ke leher yang menyatukan rangka elips yang menahan matriks senar yang ditarik dengan kencang. Selama 100 tahun pertama permainan modern, raket terbuat dari kayu dan berukuran standar, dan senarnya terbuat dari usus hewan. Konstruksi kayu laminasi menghasilkan kekuatan yang lebih besar pada raket yang digunakan sepanjang sebagian besar abad ke-20 hingga logam pertama dan kemudian komposit dari karbon grafit, keramik, dan logam yang lebih ringan seperti titanium diperkenalkan. Bahan yang lebih kuat ini memungkinkan produksi raket berukuran besar yang menghasilkan tenaga yang lebih besar. Sementara itu, teknologi mengarah pada penggunaan senar sintetis yang sesuai dengan rasa usus tetapi dengan daya tahan tambahan."
}
@sport3.save
puts "new Sport: #{@sport3.name}"

# Article Sport 4
@sport4 = Sport.new(name: "Pickleball")
@sport4.image.attach(io: Rails.root.join("vendor/assets/images/banners/banner-grey.png").open, filename: "banner-grey.png")
@sport4.short_description = "Pickleball is a racket or paddle sport in which two or four players use a smooth-faced paddle to hit a perforated, hollow plastic ball over a 34-inch-high (0.86 m) net until one side is unable to return the ball or commits a rule infraction. Pickleball is played indoors and outdoors. It was invented in 1965 as a children's backyard game in the United States, on Bainbridge Island in Washington state. In 2021, pickleball was named the official state sport of Washington."
@sport4.description = "Aspects of the sport resemble tennis and table tennis played on a doubles badminton court, but pickleball has specific scoring rules, paddles, balls and court lines. On each side of the net is a 7-foot area (2.1 m) known as the non-volley zone (or kitchen); a player standing there may not strike the ball before it has bounced. The hard plastic pickleball produces less bounce than a tennis ball. The limited bounce, non-volley zones, and underhanded stroke, with which all serves must be made, give the game a dynamic pace.[2] Slow soft shots in the non-volley zone, called dinks, are used to limit the opponent's ability to attack, while balls that are returned too high might be struck with a powerful and fast drive or overhead smash shot."
@sport4.save
Mobility.with_locale(:id) {
  @sport4.short_description = "Pickleball adalah olahraga raket atau dayung di mana dua atau empat pemain menggunakan dayung bermuka halus untuk memukul bola plastik berlubang dan berongga di atas jaring setinggi 34 inci (0,86 m) hingga satu pihak tidak dapat mengembalikan bola atau melakukan pelanggaran aturan. Pickleball dimainkan di dalam dan luar ruangan. Permainan ini ditemukan pada tahun 1965 sebagai permainan halaman belakang anak-anak di Amerika Serikat, di Pulau Bainbridge di negara bagian Washington. Pada tahun 2021, pickleball ditetapkan sebagai olahraga resmi negara bagian Washington."
  @sport4.description = "Aspek dari olahraga ini menyerupai tenis dan tenis meja yang dimainkan di lapangan bulu tangkis ganda, tetapi pickleball memiliki aturan penilaian, dayung, bola, dan garis lapangan yang spesifik. Di setiap sisi net terdapat area seluas 7 kaki (2,1 m) yang dikenal sebagai zona non-voli (atau dapur); pemain yang berdiri di sana tidak boleh memukul bola sebelum memantul. Pickleball plastik keras menghasilkan pantulan yang lebih sedikit daripada bola tenis. Pantulan terbatas, zona non-voli, dan pukulan underhanded, yang harus dilakukan pada semua servis, memberikan permainan ini kecepatan yang dinamis.[2] Pukulan lembut lambat di zona non-voli, yang disebut dinks, digunakan untuk membatasi kemampuan lawan untuk menyerang, sementara bola yang dikembalikan terlalu tinggi dapat dipukul dengan drive yang kuat dan cepat atau pukulan smash overhead."
}
@sport4.save
puts "new Sport: #{@sport4.name}"
